sequenceDiagram
    Browser->>+CloudFront: admin tool url: request index.html
    CloudFront->>WAF: Check Access
    Note right of WAF: Access restricted to CDL
    WAF->>CloudFront: Access Granted
    CloudFront->>S3: Retrieve Assets (html, js, css)
    S3->>CloudFront: Return Web Assets
    Note right of CloudFront: Cache time is set to zero for the admin tool
    CloudFront->>Browser: Return Web Assets
    Note right of Browser: html/css: page display
    Note right of Browser: js: page logic to create ajax requests
    Browser->>ALB: ajax call (HttpRequest) to invoke lambda
    ALB->>WAF: Check Access
    Note right of WAF: Access restricted to CDL
    WAF->>ALB: Access Granted
    ALB->>Lambda: Send GET/POST params as JSON payload
    Lambda->>ALB: Return JSON payload
    ALB->>Browser: Return HttpResponse
    Note right of Browser: js: render response payload as admin report

