%%{init: {'theme': 'neutral', 'securityLevel': 'loose'}}%%
graph TD
  ADMIN{{Admin Tool - Lambda}}
  click ADMIN href "https://github.com/CDLUC3/mrt-admin-lambda" "source code"
  ADMINWEB[[Admin Tool - SPA - Browser]]
  click ADMINWEB href "https://github.com/CDLUC3/mrt-admin-lambda" "source code"
  WAF[Web application Firewall]
  CF[Cloud Front]
  S3WEB[[S3 Hosted Website]]

  subgraph flowchart
    ALB --> ADMIN
    ADMIN --> |json| ALB
    ADMINWEB --> |ajax| ALB
    ALB --> |json| ADMINWEB
    CF --> ADMINWEB
    CF --> |authorize| WAF
    S3WEB --> CF
  end
  style ADMIN stroke:red,stroke-width:4px
  style ADMINWEB stroke:red,stroke-width:4px
  style ALB fill:cyan
  style WAF fill:cyan
  style CF fill:cyan
  style S3WEB fill:#77913C