%%{init: {'theme': 'neutral', 'securityLevel': 'loose'}}%%
graph TD
  RDS[(Inventory DB)]
  AUDIT(AUDIT - Fixity Check)
  click AUDIT href "https://github.com/CDLUC3/mrt-audit" "source code"

  subgraph flowchart
    subgraph cloud_storage
      CLDS3[/AWS S3/]
      CLDSDSC[/SDSC Minio/]
      CLDWAS[/Wasabi/]
      CLDGLC[/Glacier/]
    end

    RDS --> |acquire work| AUDIT
    AUDIT --> |fixity check| CLDS3
    AUDIT --> |metadata check| CLDGLC
    AUDIT --> |fixity check| CLDWAS
    AUDIT --> |fixity check| CLDSDSC
    AUDIT -.-> |record fixity| RDS
  end
  style CLDS3 fill:#77913C
  style CLDGLC fill:#77913C
  style CLDSDSC fill:#77913C
  style CLDWAS fill:#77913C
  style RDS fill:#F68D2F

  style AUDIT stroke:red,stroke-width:4px