%%{init: {'theme': 'neutral'}}%%
graph TD
  RDSINV[(Inventory Database)]
  RDSBILL[(Billing Database)]
  BILLCRON[[Cron: Billing]]

  subgraph flowchart
    BILLCRON --> |aggregation query| RDSINV
    BILLCRON --> |daily update| RDSBILL
  end

  style RDSINV fill:#F68D2F
  style RDSBILL fill:#F68D2F
  style BILLCRON stroke:red,stroke-width:4px