%%{init: {'theme': 'neutral'}}%%
graph TD
  subgraph flowchart
    subgraph inputs
      PQZIP[[Proquest Zip Files]]
      PQMARC[[Proquest Unx Files]]
    end
    subgraph outputs
      MARC[[Generated Marc Files]]
    end

    CONVPQ(Convert ProQuest Zip Files - getetds.py)
    CONVM(Enhance Unx/Marc - createmarc.py)
    DB[(SQL Lite DB)]
    MI(Merritt Ingest)
    M((Merritt))
    CM(Create Marc - createmarc.py)
    PQH(ProQuest Gateway Harvest - pqgateway.py)
    EMPQ(Enhance Marc with Isbn - createmarc.py)
    EH(EScholarship Feed)
    E((EScholarship))
    PQG((Proquest Gateway))
    M2E(Merrit to Escholarship Harvest)
    DELM(Deliver Marc to Campuses - createmarc.py)

    PQZIP --> CONVPQ
    CONVPQ --> DB
    CONVPQ --> MI
    PQMARC --> CONVM
    DB --> CONVM
    DB --> EMPQ
    DB --> CONVM
    CONVM --> |add campus fields| MARC
    MARC --> MI
    MI --> M
    CM --> |calls| EH
    CM --> |add eschol link and campus fields| MARC
    EMPQ --> |add isbn and PQ url| MARC

    M --> M2E
    M2E --> E
    E --> EH
    EH -.-> |get escholarship link| DB
    EH --> MI

    PQG --> PQH
    PQH --> DB
    MARC --> DELM

    style EMPQ fill:lime
    style CM fill:lime
    style CONVM fill:lime
    style CONVPQ fill:lime
    style PQH fill:lime
    style M2E fill:cyan
  end