%%{init: {'theme': 'neutral'}}%%
graph TD
  CAPY{{Capybara Test Driver Container}}
  CHROME{{Headless Chrome Container}}
  UI(Merritt UI)
  STORE(Storage)
  CONFIG[[Test Config Yaml]]
  DOCK(Docker Compose)

  subgraph flowchart
    DOCK -.-> |docker run| CAPY
    DOCK -.-> |docker run| CHROME
    CONFIG --> CAPY
    CAPY --> CHROME
    CHROME --> |http| UI
    CHROME --> |http| STORE
  end
  
  style DOCK fill:cyan
  style CHROME fill:cyan
  style CAPY stroke:red,stroke-width:4px