%%{init: {'theme': 'neutral', 'securityLevel': 'loose'}}%%
graph TD
  UI("Merritt UI")
  click UI href "https://github.com/CDLUC3/mrt-dashboard" "source code"
  LDAP[/LDAP\]
  SWORD(Sword)
  click SWORD href "https://github.com/CDLUC3/mrt-sword" "source code"
  COLLADMIN([Collection Admin - Lambda])
  click COLLADMIN href "https://github.com/CDLUC3/mrt-admin-lambda" "source code"

  subgraph Merritt
    UI --> |authorization| LDAP
    SWORD --> |authorization| LDAP
    COLLADMIN --> |query| LDAP
  end

  style LDAP fill:cyan
  style LDAP stroke:red,stroke-width:4px
