%%{init: {'theme': 'neutral', 'securityLevel': 'loose'}}%%
graph TD
  DRYAD(Dryad UI)
  RDS[(Inventory DB)]
  OAI(OAIPMH)

  subgraph flowchart
    RDS --> OAI
    OAI --> DRYAD
  end

  style RDS fill:#F68D2F
  style DRYAD fill:cyan
  style OAI stroke:red,stroke-width:4px