graph TD
    CLOUD((Cloud Storage<br>S3/Glacier<br>SDSC<br>Wasabi))
    RDS[(Inventory DB)]
    AUD(Audit)
    REP(Replication)
    RDS --> AUD
    RDS --> REP
    CLOUD --> AUD
    CLOUD --> REP
    REP --> CLOUD

    style CLOUD fill:green
    style RDS fill:orange
