%%{init: {'theme': 'neutral'}}%%
graph TD
  RDS[(Inventory DB)]
  UI("Merritt UI")
  ING(Ingest)
  ST(Storage)
  STACC(Storage - Access)
  INV(Inventory)
  CLOUD(("Cloud Storage"))
  LDAP[/LDAP\]
  ZOO>Zookeeper]
  EZID(EZID Service)
  BROWSER[[Browser]]

  subgraph flowchart
    BROWSER --> |ingest or retrieval| UI
    RDS --> UI
    UI --> |"file or manifest"| ING
    UI --> |authorization| LDAP
    ING --> |"async deposit"| ST
    ING --> ZOO
    ZOO --> ING
    ZOO --> INV
    UI ---> |retrieval req| STACC
    INV --> RDS
    STACC --> |retrieval req| CLOUD
    CLOUD -.-> |presigned URL| STACC
    STACC -.-> |presigned URL| UI
    ING --> EZID
    CLOUD -.-> |presigned retrieval| BROWSER
    ING -.-> |local id request| INV
    INV -.-> |retrieve manifest| ST
  end

  style CLOUD fill:#77913C
  style RDS fill:#F68D2F
  style LDAP fill:cyan
  style ZOO fill:cyan
  style EZID fill:cyan
  