graph TD
    UI[Merritt UI] -->|File or Manifest, Async| ING(Go shopping)
    UI --> RDS
    ING[Ingest] --> STORE
    STORE --> S3[S3]
    STORE --> SDSC[SDSC Minio]
    STORE --> GLACIER[S3 Glacier]
    STORE --> WASABI[Wasabi]
    STORE --> INV[Inventory]
    INV -->|foo| RDS[Inventory DB]
    DRYAD[Dryad UI] --> UI
    DRYAD --> SWORD[Sword]
    SWORD --> |Manfest, Synchronous| ING
    S3 --> AUD[Audit]
    SDSC --> AUD
    WASABI --> AUD
    AUD --> RDS
