%%{init: {'theme': 'neutral'}}%%
graph TD
  UI(Merritt UI)
  DRYAD(Dryad UI)
  RDS[(Inventory DB)]
  CLOUD(("Cloud Storage"))
  LDAP[/LDAP\]
  SWORD(Sword)
  BROWSER[[Browser]]
  ING(Ingest)

  subgraph flowchart
    BROWSER --> |retrieval req| DRYAD
    DRYAD --> |retrieval req| UI
    UI -.-> |presigned URL| DRYAD
    DRYAD --> |manifest| SWORD
    SWORD --> |deposit| ING
    SWORD --> |authorization| LDAP
    RDS --> OAI
    OAI(OAIPMH)
    OAI --> DRYAD
    CLOUD -.-> |presigned retrieval| BROWSER
  end
  style CLOUD fill:#77913C
  style RDS fill:#F68D2F
  style LDAP fill:cyan
  style DRYAD fill:cyan

