%%{init: {'theme': 'neutral', 'securityLevel': 'loose'}}%%
graph TD
  UI("Merritt UI")
  click UI href "https://github.com/CDLUC3/mrt-dashboard" "source code"
  ST(Storage - Access)
  click ST href "https://github.com/CDLUC3/mrt-store" "source code"
  BROWSER[[Browser]]

  subgraph flowchart

    subgraph cloud_storage
      CLOUD(("Cloud Storage - Primary Node"))
      click CLOUD href "https://github.com/CDLUC3/mrt-cloud" "source code"
    end

    BROWSER --> |retrieval req| UI
    UI -.-> |presigned redirect| BROWSER
    UI --> |retrieval req| ST
    ST --> |retrieval req| CLOUD
    CLOUD -.-> |presigned URL| ST
    ST -.-> |presigned URL| UI
    CLOUD -.-> |presigned retrieval| BROWSER
  end
  style CLOUD fill:#77913C
  style ST stroke:red,stroke-width:4px