%%{init: {'theme': 'neutral', 'securityLevel': 'loose'}}%%
graph TD
  SAUI("Storage Admin UI")
  SA("Storage Admin Lambda")
  REPLIC("Replication")
  RDS[(Inventory DB)]
  CLOUD(("Cloud Storage"))

  subgraph "Use Case: Crawl Storage Node for Untracked Files"
    SAUI-->SA
    SA-->|"Start Scan"|REPLIC
    CLOUD-->|"node/key list"|REPLIC
    REPLIC-->|"lookup node/key(batch)"|RDS
    REPLIC--->|"generate node/key review list"|RDS
  end

  style RDS fill:#F68D2F
  style CLOUD fill:#77913C
  
