%%{init: {'theme': 'neutral', 'securityLevel': 'loose', 'themeVariables': {'fontFamily': 'arial'}}}%%
graph TD
  ING(Ingest)
  click ING href "https://github.com/CDLUC3/mrt-ingest" "source code"
  ST(Storage)
  click ST href "https://github.com/CDLUC3/mrt-store" "source code"
  INV(Inventory)
  click INV href "https://github.com/CDLUC3/mrt-inventory" "source code"
  ZOOINV>Zookeeper Inventory]
  click ZOOINV href "https://github.com/CDLUC3/mrt-zoo" "source code"

  subgraph flowchart

    subgraph cloud_storage
      CLOUD(("Cloud Storage - Primary Node"))
      click CLOUD href "https://github.com/CDLUC3/mrt-cloud" "source code"
    end

    ING --> |deposit| ST
    INV --> |retrieve manifest| ST
    ST -.-> |manifest file| INV
    ST --> |deposit to primary node| CLOUD
    CLOUD --> |retrieve manifest| ST
    ZOOINV --> INV 
  end
  style CLOUD fill:#77913C
  style ST stroke:red,stroke-width:4px
  style ZOOINV fill:cyan