%%{init: {'theme': 'neutral', 'securityLevel': 'loose'}}%%
graph TD
  SAUI("Storage Admin UI")
  SA("Storage Admin Lambda")
  RDS[(Inventory DB)]
  REPLIC("Replication")
  CLOUD(("Cloud Storage"))

  subgraph "Use Case: Delete Keys from Cloud Storage"
    SAUI-->SA
    RDS-->|"1. Read Review List"|SA
    SA-->|"2. Approve Deletes"|RDS
    SA-->|"3. Document exceptions from review list"|RDS
    SA-->|"4. Initiate deletes"|REPLIC
    RDS-->|"5. Read Delete List"|REPLIC
    REPLIC-->|"6. Delete Cloud Objects(keys)"|CLOUD
    REPLIC-->|"7. Record Deletes"|RDS
  end

  style RDS fill:#F68D2F
  style CLOUD fill:#77913C
  
