%%{init: {'theme': 'neutral', 'securityLevel': 'loose'}}%%
graph TD
  SAUI("Storage Admin UI")
  SA("Storage Admin Lambda")
  SABUCK[/"Storage Admin Bucket"/]
  CLOUD(("Cloud Storage"))

  subgraph "Use Case: Delete Keys from Cloud Storage"
    SAUI-->SA
    SABUCK-->|"1. Read Delete List"|SA
    SA-->|"2. Delete Cloud Objects(keys)"|CLOUD
    SA-->|"3. Delete Report"|SABUCK
  end

  style SABUCK fill:#77913C
  style CLOUD fill:#77913C
  
