%%{init: {'theme': 'neutral', 'securityLevel': 'loose'}}%%
graph TD
  SAUI("Storage Admin UI")
  SA("Storage Admin Lambda")
  TBD[(SSM? / ZK?)]
  ING(Ingest)

  subgraph "Use Case: Pause Ingest for Collection"
    SAUI-->SA
    SA-->|"set paused for coll"|TBD
    ING-->|"check for paused collections"|TBD
  end

  style TBD fill:#F68D2F
