%%{init: {'theme': 'neutral', 'securityLevel': 'loose'}}%%
graph TD
  SAUI("Storage Admin UI")
  SA("Storage Admin Lambda")
  RDS[(Inventory DB)]
  INV(Inventory)
  ING(Ingest)

  subgraph "Use Case: Pause Ingest for Collection"
    SAUI-->SA
    SA-->|"set paused for coll"|RDS
    INV-->|"read paused flag for collections"|RDS
    ING-->|"check for paused collections"|INV
  end

  style RDS fill:#F68D2F
