%%{init: {'theme': 'neutral', 'securityLevel': 'loose'}}%%
graph TD
  SAUI("Storage Admin UI")
  SA("Storage Admin Lambda")
  RDS[(Inventory DB)]
  SABUCK[/"Storage Admin Bucket"/]
  CLOUD(("Cloud Storage"))

  subgraph "Use Case: Crawl Storage Node for Untracked Files"
    SAUI-->SA
    CLOUD-->|"node/key list"|SA
    SA-->|"lookup node/key(batch)"|RDS
    SA--->|"node/key delete list"|SABUCK
  end

  style RDS fill:#F68D2F
  style SABUCK fill:#77913C
  style CLOUD fill:#77913C
  
