%%{init: {'theme': 'neutral'}}%%
graph TD
  ING(Ingest)
  ST(Storage)
  INV(Inventory)
  ZOOINV>Zookeeper Inventory]

  subgraph flowchart

    subgraph cloud_storage
      CLOUD(("Cloud Storage - Primary Node"))
    end

    ING --> |deposit| ST
    INV --> |retrieve manifest| ST
    ST -.-> |manifest file| INV
    ST --> |deposit to primary node| CLOUD
    CLOUD --> |retrieve manifest| ST
    ZOOINV --> INV 
  end
  style CLOUD fill:#77913C
  style ST stroke:red,stroke-width:4px
  style ZOOINV fill:cyan