%%{init: {'theme': 'neutral', 'securityLevel': 'loose'}}%%
graph TD
  SAUI("Storage Admin UI")
  SA("Storage Admin Lambda")
  REPLIC(Replication)
  ST(Storage)
  INV(Inventory)
  EZID

  subgraph "Use Case: Remove Object from Storage and Inventory"
    SAUI-->SA
    SA-->|"1. del sec copy"|REPLIC
    SA-->|"2. del prim copy"|ST
    SA-->|"3. del from inventory"|INV
    SA-->|"4. del localid"|INV
    SA-->|"5. update EZID?"|EZID
  end  

  style EZID fill:cyan