%%{init: {'theme': 'neutral'}}%%
graph TD
  DRYAD(Dryad UI)
  LDAP[/LDAP\]
  SWORD(Sword)
  ING(Ingest)

  subgraph flowchart
    DRYAD --> |manifest| SWORD
    SWORD --> |deposit| ING
    SWORD --> |authorization| LDAP
  end
  style LDAP fill:cyan
  style DRYAD fill:cyan
  style SWORD stroke:red,stroke-width:4px