%%{init: {'theme': 'neutral', 'securityLevel': 'loose'}}%%
graph TD
  DRYAD(Dryad UI)
  LDAP[/LDAP\]
  SWORD(Sword)
  ING(Ingest)
  click ING href "https://github.com/CDLUC3/mrt-ingest" "source code"
  RDS[(Inventory DB)]

  subgraph flowchart
    DRYAD --> |manifest| SWORD
    SWORD --> |deposit| ING
    SWORD --> |authorization| LDAP
    SWORD --> |collection lookup| RDS
  end
  style LDAP fill:cyan
  style DRYAD fill:cyan
  style SWORD stroke:red,stroke-width:4px
  style RDS fill:#F68D2F
