---
swagger: "2.0"
info:
  description: Merritt User Interface API
  version: 1.0.0
  title: Merritt User Interface API
host: merritt.cdlib.org
basePath: /terrywbrady/Merritt/1.0.0
tags:
- name: ui
  description: Merritt UI
- name: api
  description: Merritt API
- name: deprecated
  description: Deprecated API calls
schemes:
- https
paths:
  /login:
    get:
      tags:
      - ui
    post:
      tags:
      - ui
  /guest_login:
    get:
      tags:
      - ui
    post:
      tags:
      - ui
  /logout:
    get:
      tags:
      - ui
  /m/{ark}:
    get:
      tags:
      - ui
      parameters: 
      - in: path
        name: ark
        type: string
        required: true
  /m/{ark}/{version}:
    get:
      tags:
      - ui
      parameters: 
      - in: path
        name: ark
        type: string
        required: true
      - in: path
        name: version
        type: integer
        required: true
  /home/choose_collection:
    get:
      tags:
      - ui
  /user/update:
    get:
      tags:
      - ui
  /collection/search_results:
    get:
      tags:
      - ui
  /version/index:
    get:
      tags:
      - ui
  /a/{ark}:
    get:
      tags:
      - ui
      parameters: 
      - in: path
        name: ark
        type: string
        required: true
  /collection/object_count:
    get:
      tags:
      - ui
  /collection/version_count:
    get:
      tags:
      - ui
  /collection/file_count:
    get:
      tags:
      - ui
  /collection/total_size:
    get:
      tags:
      - ui
  /collection/billable_size:
    get:
      tags:
      - ui
  /d/{ark}/{version}/{file}:
    get:
      tags:
      - deprecated
      parameters: 
      - in: path
        name: ark
        type: string
        required: true
      - in: path
        name: version
        type: integer
        required: true
      - in: path
        name: file
        type: string
        required: true
  /d/{ark}/{version}:
    get:
      tags:
      - deprecated
      parameters: 
      - in: path
        name: ark
        type: string
        required: true
      - in: path
        name: version
        type: integer
        required: true
  /d/{ark}:
    get:
      tags:
      - deprecated
      parameters: 
      - in: path
        name: ark
        type: string
        required: true
  /u/{ark}/{version}:
    get:
      tags:
      - deprecated
      parameters: 
      - in: path
        name: ark
        type: string
        required: true
      - in: path
        name: version
        type: integer
        required: true
  /u/{ark}:
    get:
      tags:
      - deprecated
      parameters: 
      - in: path
        name: ark
        type: string
        required: true
  /dm/{ark}:
    get:
      tags:
      - deprecated
      parameters: 
      - in: path
        name: ark
        type: string
        required: true
  /feeds/recent:
    get:
      tags:
      - deprecated
  /object/recent.{feedtype}:
    get:
      tags:
      - ui
      parameters: 
      - in: path
        name: feedtype
        type: string
        required: true
  /api/presign-file/{ark}/{version}/{file}:
    get:
      tags:
      - api
      parameters: 
      - in: path
        name: ark
        type: string
        required: true
      - in: path
        name: version
        type: integer
        required: true
      - in: path
        name: file
        type: string
        required: true
  /api/get-storage-key-file/{ark}/{version}/{file}:
    get:
      tags:
      - deprecated
      parameters: 
      - in: path
        name: ark
        type: string
        required: true
      - in: path
        name: version
        type: integer
        required: true
      - in: path
        name: file
        type: string
        required: true
  /api/assemble-version/{ark}/{version}:
    get:
      tags:
      - api
      parameters: 
      - in: path
        name: ark
        type: string
        required: true
      - in: path
        name: version
        type: integer
        required: true
  /api/assemble-obj/{ark}:
    get:
      tags:
      - api
      parameters: 
      - in: path
        name: ark
        type: string
        required: true
  /api/presign-obj-by-token/{token}:
    get:
      tags:
      - api
      parameters: 
      - in: path
        name: token
        type: string
        required: true
  /object/ingest:
    post:
      tags:
      - ui
      - api
  /object/update:
    post:
      tags:
      - ui
      - api
  /object/mint:
    post:
      tags:
      - ui
      - api
  /object/upload:
    post:
      tags:
      - ui
      - api
