# This is a basic workflow to help you get started with Actions

name: Add New Issue to Project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/cdluc3/projects/5
          #github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
