name: 'Mermaid PR Render'

on: 
  push:
    branches:
      - mermaid
    #paths:
    #  # Limit action runs to PRs that have Mermaid files (you can change to whatever suffix you use)
    #  - 'diagrams/*.md'

jobs:
  render-md-mermaid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Render images for every Mermaid diagram in all Markdown files (*.md) in the repo
        uses: nielsvaneck/render-md-mermaid@v1

      - name: Commit rendered png and svg files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "*[.svg,.png]"
          commit_message: automatically rendered mermaid diagrams